const cats = [
  {
    id: 1,
    name: "Bella",
    age: 4,
    gender: "Female",
    breed: "British Shorthair",
    location: "Tierheim 1",
    image: "/images/cat1.jpg",
  },
  {
    id: 2,
    name: "Max",
    age: 2,
    gender: "Male",
    breed: "Maine Coon",
    location: "Tierheim 2",
    image: "/images/cat2.jpg",
  },
  {
    id: 3,
    name: "Luna",
    age: 1,
    gender: "Female",
    breed: "Persian",
    location: "Tierheim 1",
    image: "/images/cat3.jpg",
  },
  {
    id: 4,
    name: "Oscar",
    age: 3,
    gender: "Male",
    breed: "Siamese",
    location: "Tierheim 3",
    image: "/images/cat4.jpg",
  },
  {
    id: 5,
    name: "Lucy",
    age: 5,
    gender: "Female",
    breed: "Ragdoll",
    location: "Tierheim 2",
    image: "/images/cat5.jpg",
  },
  {
    id: 6,
    name: "Leo",
    age: 2,
    gender: "Male",
    breed: "Bengal",
    location: "Tierheim 1",
    image: "/images/cat6.jpg",
  },
  {
    id: 7,
    name: "Mia",
    age: 4,
    gender: "Female",
    breed: "Sphynx",
    location: "Tierheim 3",
    image: "/images/cat7.jpg",
  },
  {
    id: 8,
    name: "Charlie",
    age: 3,
    gender: "Male",
    breed: "Scottish Fold",
    location: "Tierheim 2",
    image: "/images/cat8.jpg",
  },
  {
    id: 9,
    name: "Sophie",
    age: 1,
    gender: "Female",
    breed: "Norwegian Forest",
    location: "Tierheim 1",
    image: "/images/cat9.jpg",
  },
  {
    id: 10,
    name: "Oliver",
    age: 2,
    gender: "Male",
    breed: "Siberian",
    location: "Tierheim 3",
    image: "/images/cat10.jpg",
  },
];

export default cats;
