const cats = [
  {
    id: 1,
    name: "Bella",
    age: 4,
    gender: "Weiblich",
    breed: "British Shorthair",
    location: "Tierheim 1",
    image: "/images/cats/cat1.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Bella ist eine liebevolle und verspielte Katze. Sie liebt es, mit Bällen zu spielen und gekrault zu werden. Bella ist stubenrein und sucht ein neues Zuhause.",
  },
  {
    id: 2,
    name: "Max",
    age: 2,
    gender: "Männlich",
    breed: "Maine Coon",
    location: "Tierheim 2",
    image: "/images/cats/cat2.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Max ist ein großer und majestätischer Kater. Er ist sehr sozial und verträgt sich gut mit anderen Katzen. Max ist geimpft und kastriert.",
  },
  {
    id: 3,
    name: "Luna",
    age: 1,
    gender: "Weiblich",
    breed: "Persian",
    location: "Tierheim 1",
    image: "/images/cats/cat3.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Luna ist eine wunderschöne Perserkatze mit seidigem Fell. Sie ist ruhig und liebevoll und liebt es, auf dem Schoß zu kuscheln. Luna ist auch für Allergiker geeignet.",
  },
  {
    id: 4,
    name: "Oscar",
    age: 3,
    gender: "Männlich",
    breed: "Siamese",
    location: "Tierheim 3",
    image: "/images/cats/cat4.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Oscar ist ein verspielter Siamese mit blauen Augen. Er ist intelligent und lernt gerne neue Tricks. Oscar sucht eine aktive Familie, die viel mit ihm spielt.",
  },
  {
    id: 5,
    name: "Lucy",
    age: 5,
    gender: "Weiblich",
    breed: "Ragdoll",
    location: "Tierheim 2",
    image: "/images/cats/cat5.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Lucy ist eine sanfte und liebevolle Ragdoll-Katze. Sie genießt ruhige Momente und mag es, gebürstet zu werden. Lucy ist auch gut mit Kindern verträglich.",
  },
  {
    id: 6,
    name: "Leo",
    age: 2,
    gender: "Männlich",
    breed: "Tortie",
    location: "Tierheim 1",
    image: "/images/cats/cat6.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Leo ist ein lebhafter und abenteuerlustiger Bengal-Kater. Er liebt es, draußen zu spielen und zu erkunden. Leo ist kastriert und gechipt.",
  },
  {
    id: 7,
    name: "Mia",
    age: 4,
    gender: "Weiblich",
    breed: "European Shorthair",
    location: "Tierheim 3",
    image: "/images/cats/cat7.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Mia ist eine einzigartige Sphynx-Katze ohne Fell. Sie ist freundlich und aufgeschlossen und benötigt gelegentlich eine spezielle Hautpflege. Mia ist stubenrein und geimpft.",
  },
  {
    id: 8,
    name: "Charlie",
    age: 3,
    gender: "Männlich",
    breed: "Scottish Fold",
    location: "Tierheim 2",
    image: "/images/cats/cat8.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Charlie ist ein charmanter Scottish Fold-Kater. Er hat einen besonderen geknickten Ohren und ist sehr verspielt. Charlie ist stubenrein und sucht ein liebevolles Zuhause.",
  },
  {
    id: 9,
    name: "Sophie",
    age: 1,
    gender: "Weiblich",
    breed: "Norwegian Forest",
    location: "Tierheim 1",
    image: "/images/cats/cat9.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Sophie ist eine verspielte und aktive Norwegian Forest-Katze. Sie liebt es, in der Natur herumzustreifen und zu klettern. Sophie ist geimpft und kastriert.",
  },
  {
    id: 10,
    name: "Oliver",
    age: 2,
    gender: "Männlich",
    breed: "Siberian",
    location: "Tierheim 3",
    image: "/images/cats/cat10.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Oliver ist ein hübscher Siberian-Kater mit dichtem Fell. Er ist sehr sozial und liebt es, mit anderen Katzen zu spielen. Oliver sucht ein liebevolles Zuhause.",
  },
];

export default cats;
