const dogs = [
  {
    id: 11,
    name: "Charlie",
    age: 3,
    gender: "Männlich",
    breed: "German Shepherd",
    location: "Tierheim 2",
    image: "/images/dog2.jpg",
  },
  {
    id: 12,
    name: "Max",
    age: 2,
    gender: "Männlich",
    breed: "Labrador Retriever",
    location: "Tierheim3",
    image: "/images/dog1.jpg",
  },
  {
    id: 13,
    name: "Luna",
    age: 7,
    gender: "Weiblich",
    breed: "Golden Retriever",
    location: "Tierheim 1",
    image: "/images/dog3.jpg",
  },
  {
    id: 14,
    name: "Buddy",
    age: 4,
    gender: "Männlich",
    breed: "Poodle",
    location: "Tierheim 2",
    image: "/images/dog4.jpg",
  },
  {
    id: 15,
    name: "Daisy",
    age: 2,
    gender: "Weiblich",
    breed: "Beagle",
    location: "Tierheim 3",
    image: "/images/dog5.jpg",
  },
  {
    id: 16,
    name: "Rocky",
    age: 5,
    gender: "Männlich",
    breed: "Bulldog",
    location: "Tierheim 1",
    image: "/images/dog6.jpg",
  },
  {
    id: 17,
    name: "Coco",
    age: 3,
    gender: "Weiblich",
    breed: "Chihuahua",
    location: "Tierheim 2",
    image: "/images/dog7.jpg",
  },
  {
    id: 18,
    name: "Maximus",
    age: 4,
    gender: "Männlich",
    breed: "Rottweiler",
    location: "Tierheim 3",
    image: "/images/dog8.jpg",
  },
  {
    id: 19,
    name: "Molly",
    age: 1,
    gender: "Weiblich",
    breed: "Siberian Husky",
    location: "Tierheim 1",
    image: "/images/dog9.jpg",
  },
  {
    id: 20,
    name: "Rocky",
    age: 2,
    gender: "Männlich",
    breed: "Boxer",
    location: "Tierheim 2",
    image: "/images/dog10.jpg",
  },
];

export default dogs;
