const dogs = [
  {
    id: 11,
    name: "Charlie",
    age: 1,
    gender: "Männlich",
    breed: "Labrador Retriever",
    location: "Tierheim Hamburg",
    image: "/images/dogs/dog1.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Charlie ist ein verspielter und freundlicher Labrador-Retriever. Er ist kinderlieb und verträgt sich gut mit anderen Tieren. Max sucht ein liebevolles Zuhause mit viel Platz zum Toben.",
  },
  {
    id: 12,
    name: "Max",
    age: 3,
    gender: "Männlich",
    breed: "Mischling",
    location: "Tierheim Berlin",
    image: "/images/dogs/dog2.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Max ist ein intelligenter und treuer Begleiter. Er ist gut erzogen und verträgt sich gut mit anderen Hunden. Charlie liebt lange Spaziergänge und sucht eine aktive Familie.",
  },
  {
    id: 13,
    name: "Luna",
    age: 7,
    gender: "Weiblich",
    breed: "Golden Retriever",
    location: "Tierheim Saarbrücken",
    image: "/images/dogs/dog3.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Luna ist eine sanfte und geduldige Golden Retriever-Hündin. Sie ist gut erzogen und liebt es, mit Kindern zu spielen. Luna sucht eine Familie, die viel Zeit für sie hat.",
  },
  {
    id: 14,
    name: "Buddy",
    age: 4,
    gender: "Männlich",
    breed: "Poodle",
    location: "Tierheim Hamburg",
    image: "/images/dogs/dog4.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Buddy ist ein intelligenter und verspielter Pudel. Er ist nicht haarend und daher auch für Allergiker geeignet. Buddy ist stubenrein und sucht eine liebevolle Familie.",
  },
  {
    id: 15,
    name: "Daisy",
    age: 2,
    gender: "Weiblich",
    breed: "Beagle",
    location: "Tierheim Berlin",
    image: "/images/dogs/dog5.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Daisy ist eine fröhliche und aktive Beagle-Hündin. Sie liebt es, draußen zu sein und neue Gerüche zu erkunden. Daisy sucht eine Familie, die viel Zeit für gemeinsame Aktivitäten hat.",
  },
  {
    id: 16,
    name: "Rocky",
    age: 5,
    gender: "Männlich",
    breed: "Bulldog",
    location: "Tierheim Saarbrücken",
    image: "/images/dogs/dog6.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Rocky ist ein muskulöser und freundlicher Bulldog. Er ist gut erzogen und verträgt sich gut mit anderen Hunden. Rocky sucht eine Familie mit Hundeerfahrung.",
  },
  {
    id: 17,
    name: "Coco",
    age: 3,
    gender: "Weiblich",
    breed: "Chihuahua",
    location: "Tierheim Hamburg",
    image: "/images/dogs/dog7.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Coco ist ein kleiner und lebhafter Chihuahua. Sie ist verspielt und hat einen großen Charakter. Coco sucht eine liebevolle Familie, die sie verwöhnen kann.",
  },
  {
    id: 18,
    name: "Maximus",
    age: 4,
    gender: "Männlich",
    breed: "Pinscher",
    location: "Tierheim Berlin",
    image: "/images/dogs/dog8.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Maximus ist ein imposanter und loyaler Pinscher. Er ist gut erzogen und verfügt über ausgezeichnete Schutzeigenschaften. Maximus sucht erfahrene Hundebesitzer.",
  },
  {
    id: 19,
    name: "Molly",
    age: 1,
    gender: "Weiblich",
    breed: "Siberian Husky",
    location: "Tierheim Saarbrücken",
    image: "/images/dogs/dog9.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Molly ist eine energiegeladene und verspielte Siberian Husky-Hündin. Sie liebt es, lange Spaziergänge zu machen und im Freien aktiv zu sein. Molly sucht eine aktive Familie mit Husky-Erfahrung.",
  },
  {
    id: 20,
    name: "Leyla",
    age: 2,
    gender: "Weiblich",
    breed: "Mischling",
    location: "Tierheim Hamburg",
    image: "/images/dogs/dog10.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Rocky ist eine kräftige und verspielte Mischlingshündin. Sie ist kinderlieb und hat einen ausgeglichenen Charakter. Leyla sucht eine aktive Familie mit viel Platz zum Toben.",
  },
];

export default dogs;
