const smallanimals = [
  {
    id: 21,
    name: "Bernd",
    age: 37,
    gender: "Männlich",
    breed: "Turtle",
    location: "Tierheim Berlin",
    image: "/images/smallanimals/smallanimals1.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Bernd ist eine ruhige und gelassene Schildkröte. Er genießt es, in der Sonne zu liegen und sich in seinem Gehege zu bewegen. Bernd sucht ein Zuhause mit einem geräumigen Gehege und viel Liebe.",
  },
  {
    id: 22,
    name: "Hopsi",
    age: 2,
    gender: "Weiblich",
    breed: "Kaninchen",
    location: "Tierheim Saarbrücken",
    image: "/images/smallanimals/smallanimals2.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Hopsi ist ein aktives und neugieriges Kaninchen. Sie liebt es, ihr Gehege zu erkunden und mit Spielzeug zu spielen. Hopsi sucht ein Zuhause mit viel Platz zum Hoppeln und einem Kaninchenfreund zum Spielen.",
  },
  {
    id: 23,
    name: "Flocke",
    age: 1,
    gender: "Weiblich",
    breed: "Meerschweinchen",
    location: "Tierheim Hamburg",
    image: "/images/smallanimals/smallanimals3.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Flocke ist ein freundliches und zutrauliches Meerschweinchen. Sie liebt es, gestreichelt zu werden und frisches Gemüse zu knabbern. Flocke sucht ein Zuhause mit einem geräumigen Gehege und einem Meerschweinchenfreund zum Kuscheln.",
  },
  {
    id: 24,
    name: "Pip",
    age: 3,
    gender: "Männlich",
    breed: "Wellensittich",
    location: "Tierheim Berlin",
    image: "/images/smallanimals/smallanimals4.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Pip ist ein lebhafter und geselliger Wellensittich. Er liebt es, zu singen und zu zwitschern und sucht ein Zuhause mit einem geräumigen Käfig und einem Wellensittichfreund zum Plaudern.",
  },
  {
    id: 25,
    name: "Sammy",
    age: 4,
    gender: "Männlich",
    breed: "Hamster",
    location: "Tierheim Saarbrücken",
    image: "/images/smallanimals/smallanimals5.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Sammy ist ein aktiver und neugieriger Hamster. Er liebt es, in seinem Laufrad zu rennen und sein Gehege zu erkunden. Sammy sucht ein Zuhause mit einem geräumigen Gehege und viel Beschäftigung.",
  },
  {
    id: 26,
    name: "Mia",
    age: 2,
    gender: "Weiblich",
    breed: "Zwergkaninchen",
    location: "Tierheim Hamburg",
    image: "/images/smallanimals/smallanimals6.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Mia ist ein süßes und zutrauliches Zwergkaninchen. Sie liebt es, gestreichelt zu werden und frisches Gemüse zu knabbern. Mia sucht ein Zuhause mit viel Platz zum Hoppeln und einem Kaninchenfreund zum Kuscheln.",
  },
  {
    id: 27,
    name: "Lucky",
    age: 1,
    gender: "Männlich",
    breed: "Zebrafink",
    location: "Tierheim Berlin",
    image: "/images/smallanimals/smallanimals7.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Lucky ist ein lebhafter und geselliger Zebrafink. Er liebt es, zu singen und zu zwitschern und sucht ein Zuhause mit einem geräumigen Käfig und einem Zebrafinkfreund zum Plaudern.",
  },
  {
    id: 28,
    name: "Fluffy",
    age: 3,
    gender: "Weiblich",
    breed: "Maus",
    location: "Tierheim Saarbrücken",
    image: "/images/smallanimals/smallanimals8.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Fluffy ist eine süße kleine Maus, die gerne ihr Gehege erkundet. Sie ist neugierig und verspielt, aber auch schüchtern. Fluffy sucht ein liebevolles Zuhause mit vielen Verstecken.",
  },
  {
    id: 29,
    name: "Charlie",
    age: 2,
    gender: "Männlich",
    breed: "Wellensittich",
    location: "Tierheim Hamburg",
    image: "/images/smallanimals/smallanimals9.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Charlie ist ein geselliger und aktiver Wellensittich. Er liebt es, zu singen und zu zwitschern und sucht ein Zuhause mit einem geräumigen Käfig und einem Wellensittichfreund zum Plaudern.",
  },
  {
    id: 30,
    name: "Lola",
    age: 1,
    gender: "Weiblich",
    breed: "Kaninchen",
    location: "Tierheim Berlin",
    image: "/images/smallanimals/smallanimals10.jpg",
    imageWidth: 250,
    imageHeight: 250,
    infoText:
      "Lola ist ein freundliches und aktives Kaninchen. Sie liebt es, ihr Gehege zu erkunden und mit Spielzeug zu spielen. Lola sucht ein Zuhause mit viel Platz zum Hoppeln und einem Kaninchenfreund zum Spielen.",
  },
];
export default smallanimals;
