const smallanimals = [
  {
    id: 21,
    name: "Bernd",
    age: 37,
    gender: "Male",
    breed: "Turtle",
    location: "Tierheim 3",
  },
  {
    id: 22,
    name: "Hopsi",
    age: 2,
    gender: "Weiblich",
    breed: "Kaninchen",
    location: "Tierheim 1",
  },
  {
    id: 23,
    name: "Flocke",
    age: 1,
    gender: "Weiblich",
    breed: "Meerschweinchen",
    location: "Tierheim 2",
  },
  {
    id: 24,
    name: "Pip",
    age: 3,
    gender: "Männlich",
    breed: "Wellensittich",
    location: "Tierheim 3",
  },
  {
    id: 25,
    name: "Sammy",
    age: 4,
    gender: "Männlich",
    breed: "Hamster",
    location: "Tierheim 1",
  },
  {
    id: 26,
    name: "Mia",
    age: 2,
    gender: "Weiblich",
    breed: "Zwergkaninchen",
    location: "Tierheim 2",
  },
  {
    id: 27,
    name: "Lucky",
    age: 1,
    gender: "Männlich",
    breed: "Zebrafink",
    location: "Tierheim 3",
  },
  {
    id: 28,
    name: "Fluffy",
    age: 3,
    gender: "Weiblich",
    breed: "Maus",
    location: "Tierheim 1",
  },
  {
    id: 29,
    name: "Charlie",
    age: 2,
    gender: "Männlich",
    breed: "Wellensittich",
    location: "Tierheim 2",
  },
  {
    id: 30,
    name: "Lola",
    age: 1,
    gender: "Weiblich",
    breed: "Kaninchen",
    location: "Tierheim 3",
  },
];
export default smallanimals;
