const smallanimals = [
  {
    id: 2,
    name: "Bernd",
    age: 37,
    gender: "Male",
    breed: "Turtle",
    location: "Tierschutzbund Dortmund e.V.",
  },
  {
    id: 3,
    name: "Hopsi",
    age: 2,
    gender: "Weiblich",
    breed: "Kaninchen",
    location: "Tierheim 1",
  },
  {
    id: 4,
    name: "Flocke",
    age: 1,
    gender: "Weiblich",
    breed: "Meerschweinchen",
    location: "Tierheim 2",
  },
  {
    id: 5,
    name: "Pip",
    age: 3,
    gender: "Männlich",
    breed: "Wellensittich",
    location: "Tierheim 3",
  },
  {
    id: 6,
    name: "Sammy",
    age: 4,
    gender: "Männlich",
    breed: "Hamster",
    location: "Tierheim 1",
  },
  {
    id: 7,
    name: "Mia",
    age: 2,
    gender: "Weiblich",
    breed: "Zwergkaninchen",
    location: "Tierheim 2",
  },
  {
    id: 8,
    name: "Lucky",
    age: 1,
    gender: "Männlich",
    breed: "Zebrafink",
    location: "Tierheim 3",
  },
  {
    id: 9,
    name: "Fluffy",
    age: 3,
    gender: "Weiblich",
    breed: "Maus",
    location: "Tierheim 1",
  },
  {
    id: 10,
    name: "Charlie",
    age: 2,
    gender: "Männlich",
    breed: "Wellensittich",
    location: "Tierheim 2",
  },
  {
    id: 11,
    name: "Lola",
    age: 1,
    gender: "Weiblich",
    breed: "Kaninchen",
    location: "Tierheim 3",
  },
];
export default smallanimals;
